master: reservation-client-master.yml
message: "HELLO NAMESLESS DEPARTMENT STORE!!!!"
spring:
    cloud:
        stream:
            bindings:
                output:
                    destination: reservations