master: reservation-service-master.yml
message: "HELLO NAMESLESS DEPARTMENT STORE!!!!"
spring:
    cloud:
        stream:
            bindings:
                input: 
                    destination: reservations